apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx-app-1
  name: nginx-app-1
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-app-1
  sessionAffinity: None
  type: ClusterIP
